#got it all to be defined outside this file but I can't seem to get the configmap and the values serverport to be defined in the same place?
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
{{ .Files.Get "config.json" | indent 2}}

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: py-srv
  ports:
  - protocol: TCP
    port: 32321
    nodePort: 32321
    targetPort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: praet/python-flask:3-more
        ports:
        - containerPort: {{ .Values.SERVER_PORT }}
        env: 
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: SERVER_PORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Release.Name }}-cm
              key: SERVER_PORT_CONFIG
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.SERVER_PORT }}

