#So configmap gets mad trying to pull values from file the same way I'm doing in the pod {{value...}}, 
#but the pod doesn't seem to be able to pull it from the configmap either. Not sure what the right way to get only one value here is?
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  SERVER_PORT: "8080"

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: py-srv
  ports:
  - protocol: TCP
    port: 32321
    nodePort: 32321
    targetPort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: praet/python-flask:3-more
        ports:
        - containerPort: 8080
        env: 
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: SERVER_PORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Release.Name }}-cm
              key: SERVER_PORT
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.SERVER_PORT }}

