apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  password: {{ .Values.mysql.mysqlRootPassword }}
  SERVER_PORT_CONFIG: {{ .Values.SERVER_PORT | quote }}  
#{{ .Files.Get "config.json" | indent 2}}

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-webserver
  ports:
  - protocol: TCP
    port: 32321
    nodePort: 32321
    targetPort: 8080
  type: NodePort

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  rootPassword: {{ .Values.mysql.mysqlRootPassword | b64enc }}
  rootUsername: {{ .Values.mysql.mysqlRootUsername | b64enc }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
  labels:
    app: {{ .Release.Name }}-webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-webserver
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: praet/python-flask:3-more
        ports:
        - containerPort: {{ .Values.SERVER_PORT }}
        env: 
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: SERVER_PORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Release.Name }}-cm
              key: SERVER_PORT_CONFIG
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: rootPassword
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: rootUsername

        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.SERVER_PORT }}

