kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: py-srv
  ports:
  - protocol: TCP
    port: 32321
    nodePort: 32321
    targetPort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: praet/python-flask:3-more
        ports:
        - containerPort: 8080
        env: 
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        livenessProbe:
          httpGet:
            path: /
            port: 8080

