apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-srv-dep
  labels:
    app: py-srv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-srv
  template:
    metadata:
      labels:
        app: py-srv
    spec:
      containers:
      - name: py-srv
        image: praet/python-flask:1-make-server
        ports:
        - containerPort: 8080
