apiVersion: v1
kind: Pod
metadata:
  name: vault-test
spec:
  containers:
  - name: vaultpod
    image: vault:latest
    securityContext:
      capabilities:
        add: ["IPC_LOCK"]
    ports:
    - containerPort: 8200
    env: 
    - name: VAULT_DEV_ROOT_TOKEN_ID
      value: "myroot"
    - name: VAULT_DEV_LISTEN_ADDRESS
      value: "0.0.0.0:8200"
    - name: VAULT_ADDR
      value: "0.0.0.0:8200"
